stages:
  - deploy

variables:
  APP_VERSION: $CI_PIPELINE_IID



deploy:
  stage: deploy
  script:
    # Build the Spring Boot application
    - mvn clean install -DskipTests=true

    # Upload the JAR file to S3
    - aws s3 cp ./target/partzforless-springboot.jar s3://$AWS_S3_BUCKET/partzforless-springboot.jar
    - - export DEPLOY_TOKEN=$(echo $GITLAB_DEPLOY_TOKEN | td -d "\n" | base64)


    # Create an application version in Elastic Beanstalk
    - aws elasticbeanstalk create-application-version --application-name $APP_NAME --version-label $APP_VERSION --source-bundle S3Bucket=$AWS_S3_BUCKET,S3Key=application.jar
    # Update the environment to use the new application version
    - aws elasticbeanstalk update-environment --application-name $APP_NAME --version-label $APP_VERSION --environment-name $APP_ENV_NAME







