stages:
    - build
    - test

build laptop:
    stage: build
    variables:
        build_file_name: laptop.txt
    image: alpine
    script:
        - echo "Building a laptop"
        - mkdir build
        - touch build/$laptop.txt
        - echo "Mainboard" >> build/$laptop.txt
        - cat build/$laptop.txt
        - echo "Keyboard" >> build/$laptop.txt
        - cat build/$laptop.txt
    artifacts:
        paths:
            - build

test laptop:
    stage: test
    image: alpine
    script:
        - test -f build/$laptop.txt
        - grep "Mainboard" build/$laptop.txt
        - grep "Keyboard" build/$laptop.txt
