stages:
  - build
  - package
build project:
  image: alpine
  stage: build
  script:
    - mkdir /build
    - apk update
    - apk add maven
    - mvn clean install
  artifacts:
    paths:
      - target/*.jar
build docker image:
  stage: package
  image: docker:25.0.3
  services:
    - docker:25.0.3-dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE -t $CI_REGISTRY_IMAGE:1 .
    - docker image ls

