stages:
  - build
  - deploy
build project:
  image: alpine
  stage: build
  script:
    - mkdir /build
    - apk update
    - apk add maven
    - mvn clean install
  artifacts:
    paths:
      - target/*.jar
deploy to s3:
  stage: deploy
  image:
      name: amazon/aws-cli:2.15.25
      entrypoint: [""]
  script:
    - aws --version
    - echo "Hello s3" >> test-txt
    - aws cp test.txt s3://mygitlabcicdtestbucket/test.txt
