version: 0.2

phases:
  pre_build:
    commands:
      - echo logging into Amazon ECR started on `date`
      - aws --version
      - echo logging into Amazon ECR.....
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 741124795948.dkr.ecr.eu-central-1.amazonaws.com
      - echo setting repository URI...
      - REPOSITORY_URI=741124795948.dkr.ecr.eu-central-1.amazonaws.com/partzforless_springboot
      - echo "Setting image tag..."
      - IMAGE_TAG=build-$(echo | awk -F":" '{print $2}')

  build:
    commands:
      - echo "Building and tagging started image on $(date)"
      - echo "Running mvn clean install..."
      - mvn clean install
      - docker build -t 741124795948.dkr.ecr.eu-central-1.amazonaws.com/partzforless_springboot:latest .
      - echo "Tagging the Docker image..."
      - docker tag 741124795948.dkr.ecr.eu-central-1.amazonaws.com/partzforless_springboot:latest 741124795948.dkr.ecr.eu-central-1.amazonaws.com/partzforless_springboot:build-$(echo | awk -F":" '{print $2}')

  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR started on $(date)"
      - echo "Pushing to repository..."
      - docker push 741124795948.dkr.ecr.eu-central-1.amazonaws.com/partzforless_springboot:latest
      - docker push 741124795948.dkr.ecr.eu-central-1.amazonaws.com/partzforless_springboot:build-$(echo | awk -F":" '{print $2}')
      - echo "Setting container name..."
      - export DOCKER_CONTAINER_NAME=partzforless_springboot
      - echo "Writing image definition file..."
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
